theme: jekyll-theme-midnight
# Name of your site (displayed in the header)
title: Austin Bonander

# Short bio or description (displayed in the header)
description: Completely self-taught, Android/React-Native developer by trade, Rust hobbyist.
